# Generated by scripts/render-homebrew-ol-formula.sh — do not hand-edit; release workflow overwrites.
# frozen_string_literal: true

class Ol < Formula
  desc "Check open-source licenses in resolved dependencies and SBOMs"
  homepage "https://github.com/guitarrapc/ol"
  version "0.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.2/ol-osx-arm64.tar.gz"
      sha256 "dac172fd154abe2bd96d84b661f0c45e0337e5ee3aaa9d506e2b9c39918582b5"
    elsif Hardware::CPU.intel?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.2/ol-osx-amd64.tar.gz"
      sha256 "ce3fdbe0ebc9ac8841ee79f1b7b4b47fe8b8346de7c2d5f9f8154dd0e5c48b25"
    else
      odie "ol: unsupported macOS CPU"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.2/ol-linux-arm64.tar.gz"
      sha256 "91657e60ac41dbe8a8c07242673ba79ba0fa0472db6aa42eb5decacd0c5cb01f"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.2/ol-linux-amd64.tar.gz"
      sha256 "b97ae473a89ccbd797a96cfcdd10259be9a04a9b35e711eeef07c20f918c32f1"
    else
      odie "ol: unsupported Linux CPU"
    end
  end

  def install
    bin.install "ol"
  end

  test do
    system "#{bin}/ol", "--version"
  end
end
