# Generated by scripts/render-homebrew-ol-formula.sh — do not hand-edit; release workflow overwrites.
# frozen_string_literal: true

class Ol < Formula
  desc "Check open-source licenses in resolved dependencies and SBOMs"
  homepage "https://github.com/guitarrapc/ol"
  version "0.9.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.4/ol-osx-arm64.tar.gz"
      sha256 "594db413a0d2a14f4e66c4eac206ad6b153b387d60b0bb851eb011c92b7db8d8"
    elsif Hardware::CPU.intel?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.4/ol-osx-amd64.tar.gz"
      sha256 "8aa0540087af485caba8fc4e2e082ade20b7069bbeb6db0b1e837b3650805ed5"
    else
      odie "ol: unsupported macOS CPU"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.4/ol-linux-arm64.tar.gz"
      sha256 "8df50f6dfd427825f1e4a34423235ebb2373a7c2726285f5a2ca270cc94ee03b"
    elsif Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/guitarrapc/ol/releases/download/v0.9.4/ol-linux-amd64.tar.gz"
      sha256 "c7a4f896e09d0eacca35f4f0a5ff515b21d01ad528b9323fd2c4baed1be46fb3"
    else
      odie "ol: unsupported Linux CPU"
    end
  end

  def install
    bin.install "ol"
  end

  test do
    system "#{bin}/ol", "--version"
  end
end
