using System.Text;
using System.Text.Json;

namespace Ol.Update;

/// <summary>
/// Generates compile-time SPDX lookup data for <c>Ol.Core</c>.
/// </summary>
public static class SpdxCodeGenerator
{
    /// <summary>
    /// Generates the SPDX data source file from upstream SPDX JSON documents.
    /// </summary>
    /// <param name="licensesJson">The SPDX licenses JSON document.</param>
    /// <param name="exceptionsJson">The SPDX exceptions JSON document.</param>
    /// <returns>Deterministic C# source for <c>Ol.Core/Generated</c>.</returns>
    public static string Generate(ReadOnlySpan<byte> licensesJson, ReadOnlySpan<byte> exceptionsJson)
    {
        using var licenses = JsonDocument.Parse(SkipUtf8Bom(licensesJson).ToArray());
        using var exceptions = JsonDocument.Parse(SkipUtf8Bom(exceptionsJson).ToArray());
        var version = ReadString(licenses.RootElement, "licenseListVersion");
        var licenseIds = ReadIdentifiers(licenses.RootElement, "licenses", "licenseId");
        var exceptionIds = ReadIdentifiers(exceptions.RootElement, "exceptions", "licenseExceptionId");
        var deprecatedIds = ReadDeprecatedIdentifiers(licenses.RootElement);
        Array.Sort(licenseIds, StringComparer.Ordinal);
        Array.Sort(exceptionIds, StringComparer.Ordinal);
        Array.Sort(deprecatedIds, StringComparer.Ordinal);

        var builder = new StringBuilder();
#nullable enable
        builder.AppendLine("// <auto-generated>");
        builder.AppendLine("// This file is generated by Seiton.Update. Do not edit manually.");
        builder.AppendLine("// Regenerate: dotnet run --project src/Seiton.Update -- sync-availability");
        builder.AppendLine("// </auto-generated>");
        builder.AppendLine();
        builder.AppendLine("namespace Ol.Core.Generated;");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Generated SPDX license-list data.</summary>");
        builder.AppendLine("public static class SpdxGeneratedLicenseData");
        builder.AppendLine("{");
        builder.Append("    public const string LicenseListVersion = \"").Append(Escape(version)).AppendLine("\";");
        AppendArray(builder, "LicenseIds", licenseIds);
        builder.AppendLine();
        AppendArray(builder, "ExceptionIds", exceptionIds);
        builder.AppendLine();
        AppendArray(builder, "DeprecatedLicenseIds", deprecatedIds);
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendArray(StringBuilder builder, string name, string[] values)
    {
        builder.Append("    public static readonly string[] ").Append(name).AppendLine(" =");
        builder.AppendLine("    [");
        for (var i = 0; i < values.Length; i++)
        {
            builder.Append("        \"").Append(Escape(values[i])).AppendLine("\",");
        }

        builder.AppendLine("    ];");
    }

    private static string[] ReadIdentifiers(JsonElement root, string arrayProperty, string identifierProperty)
    {
        var values = root.GetProperty(arrayProperty);
        var result = new string[values.GetArrayLength()];
        var index = 0;
        foreach (var item in values.EnumerateArray())
        {
            result[index] = ReadString(item, identifierProperty);
            index++;
        }

        return result;
    }

    private static string[] ReadDeprecatedIdentifiers(JsonElement root)
    {
        var values = root.GetProperty("licenses");
        var deprecated = new List<string>();
        foreach (var item in values.EnumerateArray())
        {
            if (item.TryGetProperty("isDeprecatedLicenseId", out var isDeprecated) && isDeprecated.ValueKind == JsonValueKind.True)
            {
                deprecated.Add(ReadString(item, "licenseId"));
            }
        }

        return [.. deprecated];
    }

    private static string ReadString(JsonElement element, string property)
        => element.TryGetProperty(property, out var value) && value.ValueKind == JsonValueKind.String ? value.GetString() ?? string.Empty : string.Empty;

    private static ReadOnlySpan<byte> SkipUtf8Bom(ReadOnlySpan<byte> bytes)
        => bytes.Length >= 3 && bytes[0] == 0xEF && bytes[1] == 0xBB && bytes[2] == 0xBF ? bytes[3..] : bytes;

    private static string Escape(string value) => value.Replace("\\", "\\\\", StringComparison.Ordinal).Replace("\"", "\\\"", StringComparison.Ordinal);
}
