<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ol" />
    <InternalsVisibleTo Include="Ol.Benchmark" />
    <InternalsVisibleTo Include="Ol.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NuGet.Versioning" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Generated\license-texts.bin.br" LogicalName="Ol.Core.Generated.license-texts.bin.br" WithCulture="false" />
  </ItemGroup>

</Project>
